Search entity filter
alephdata/aleph-ui pull request #14
Opened 2017-08-11 13:03 UTC by wpf500

Initial work on the search filters. Added some simple CSS and implemented the basic entity filter.

- Renamed `Search` to `SearchFilter` for clarity

## TODO
- Keep count of other entities when filtered (backend API change required)
- Fix some styles (e.g. font colors) and fix Blueprint bug where the selected tab highlight doesn't update if tab text changes

![image](https://user-images.githubusercontent.com/2084823/29213361-d3eb401c-7e9a-11e7-9d84-9732b648f6fa.png)

2017-08-11 14:35 UTC, pudo requested changes
Looking good :)

2017-08-11 14:35 UTC, pudo commented on src/components/SearchFilter.js
> +  onEntityChange(type) {
Entities are real things in Aleph, and this doesn't touch them. I would call it ``onSchemaChange``?

2017-08-11 14:35 UTC, pudo commented on src/components/SearchFilter.scss
> +
Ok, this seems fair in terms of CSS. I like that you're using the $pt vars. Are you sure about the mixed _ and -- convention for CSS class names?

2017-08-11 14:35 UTC, pudo commented on src/components/SearchFilterEntities.js
> +
Ok, so all of this is about Schema, not entities (Schema applies to both entities and Documents)

2017-08-11 14:55 UTC, wpf500 commented on src/components/SearchFilter.scss
> +
http://getbem.com/introduction/ as discussed on Slack

2017-08-14 07:35 UTC, pudo approved these changes

2017-08-14 07:35 UTC, merged